const IPCCommands = {
    GET_OPEN_DATA: "GET_OPEN_DATA",
    SET_MODIFIED: "SET_MODIFIED",
    OPEN_FILE: "OPEN_FILE",
    SAVE_FILE: "SAVE_FILE",
    SAVE_AS_FILE: "SAVE_AS_FILE",
    GET_PREFERENCES: "GET_PREFERENCES",
    SET_PREFERENCES: "SET_PREFERENCES",
    GET_FILENAME: "GET_FILENAME",
    GET_MAXIMIZED_STATE: "GET_MAXIMIZED_STATE",
    CLOSE_APP: "CLOSE_APP",
    CLOSE_FILE: "CLOSE_FILE",
    MINIMIZE: "MINIMIZE",
    MAXIMIZE: "MAXIMIZE",
    UNMAXIMIZE: "UNMAXIMIZE",
}

export default IPCCommands;