name: Publish to GitHub pages

on:
    workflow_call:
        inputs:
            cache_sha:
                type: string
                required: true

jobs:
    deploy-to-pages:
        name: Deploy to GitHub pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Get dist files
              uses: actions/cache@v3
              with:
                  path: dist
                  key: dist-${{ inputs.cache_sha }}

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4.3.3
              with:
                  branch: gh-pages
                  folder: dist
                  target-folder: ${{ github.head_ref || github.ref_name }}
                  single-commit: true